/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_easyd2xx_EasyD2XX */

#ifndef _Included_com_example_easyd2xx_EasyD2XX
#define _Included_com_example_easyd2xx_EasyD2XX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_easyd2xx_EasyD2XX
 * Method:    getDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_example_easyd2xx_EasyD2XX_getDevices
  (JNIEnv *, jclass);

/*
 * Class:     com_example_easyd2xx_EasyD2XX
 * Method:    openAsFifo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_easyd2xx_EasyD2XX_openAsFifo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_easyd2xx_EasyD2XX
 * Method:    read
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_easyd2xx_EasyD2XX_read__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_easyd2xx_EasyD2XX
 * Method:    read
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_example_easyd2xx_EasyD2XX_read__Ljava_nio_ByteBuffer_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_example_easyd2xx_EasyD2XX
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_easyd2xx_EasyD2XX_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
